### ISSUE TITLE
please can we use a different word than `migrate` to avoid confusion with the internal concept of migration

### ISSUE THREAD

**Issue by twrichards** [eelpie/grid-tools#2]
https://github.com/eelpie/grid-tools/blob/ea88fc2c8c3659fd904cccf37d25fb2f8974f9f2/migrate.py#L63

'migration' is the mechanism built into thrall for (re)building a new ES index from S3 & Dynamo data, perhaps we could use a different word to refer to this selection partial copying of images & metadata?

![image](https://github.com/user-attachments/assets/3bd77404-7eec-4c40-a5ae-e01d0656eb3b)

**Comment by tonytw1** [comment]
Agree. Renaming to `copy` which better reflects what does.
It has copied images from one Grid to another; it has not moved or migrated them.

**Comment by twrichards** [comment]
> Agree. Renaming to `copy` which better reflects what does. It has copied images from one Grid to another; it has not moved or migrated them.

great, although I was hoping you'd go for expatriation 🤣
